### ISSUE TITLE
New issue - TypeError

### ISSUE THREAD

**Issue by DCPDad** [yoyostile/Plexpy-Ubersicht-Widget#6]
Hello-
I've been enjoying your PlexPy widget for quite some time, but in the past couple of days I am getting this error:
"**TypeError: undefined is not an object (evaluating 'sessions.length')**"
Any thoughts on where I should look to fix it?
Thx!

**Comment by yoyostile** [comment]
Hey,
I just pushed a new `index.coffee`. The error should be fixed in [this commit](https://github.com/yoyostile/Plexpy-Ubersicht-Widget/commit/40cbd70b82ad9900d57987a6d853c0d5de151fda).
Does it work for you?
